### ISSUE TITLE
这个数据集适合用作感知机的二分类吗

### ISSUE THREAD

**Issue by Kiwamm** [kevincho840430/Predict-5-Year-Career-Longevity-for-NBA-Rookies#1]
你好，可以问下这个数据集可以用来作为感知机的二分类吗

**Comment by kevincho840430** [comment]
這個資料集就是用現有的資訊來預測球員的職業生涯是否可以超過五年，所以是二分類沒錯(Y/N)

**Comment by Kiwamm** [comment]
> 這個資料集就是用現有的資訊來預測球員的職業生涯是否可以超過五年，所以是二分類沒錯(Y/N)

好的，谢谢了！
